// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edrxvegggschpnpnsfmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkcnh2ZWdnZ3NjaHBucG5zZm1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3MjUyOTMsImV4cCI6MjA0OTMwMTI5M30.-7dTiADMZQUfOVuMzkIPvn9AqGWYZbkDYqYwkDWg4G4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);